com::example::mybookshelf::dataClass::Book
String com.example.mybookshelf.dataClass.Book.genre
Referenced by com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.getGenre.
String com.example.mybookshelf.dataClass.Book.name
Referenced by com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.getName.
String com.example.mybookshelf.dataClass.Book.author
Referenced by com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.getAuthor, com.example.mybookshelf.dataClass.Book.setAuthor.
int com.example.mybookshelf.dataClass.Book.pages
Referenced by com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.getPages.
String com.example.mybookshelf.dataClass.Book.release_date
Referenced by com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.getRelease_date, com.example.mybookshelf.dataClass.Book.getReleaseDate, com.example.mybookshelf.dataClass.Book.setRelease_date.
String com.example.mybookshelf.dataClass.Book.image_url
Referenced by com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.getImageUrl.
String com.example.mybookshelf.dataClass.Book.description
Referenced by com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.getDescription.
boolean com.example.mybookshelf.dataClass.Book.inDatabase
Referenced by com.example.mybookshelf.dataClass.Book.isInDatabase, com.example.mybookshelf.dataClass.Book.setInDatabase.
int com.example.mybookshelf.dataClass.Book.id
Referenced by com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.Book, com.example.mybookshelf.dataClass.Book.getId.
int com.example.mybookshelf.dataClass.Book.reading_time
String com.example.mybookshelf.dataClass.Book.status
Referenced by com.example.mybookshelf.dataClass.Book.getStatus, com.example.mybookshelf.dataClass.Book.setStatus.
com.example.mybookshelf.dataClass.Book.Book(String name, String release_date, int pages, String author)
References com.example.mybookshelf.dataClass.Book.author, com.example.mybookshelf.dataClass.Book.name, com.example.mybookshelf.dataClass.Book.pages, com.example.mybookshelf.dataClass.Book.release_date.
String com.example.mybookshelf.dataClass.Book.getGenre()
Returns the genre.
References com.example.mybookshelf.dataClass.Book.genre.
Referenced by com.example.mybookshelf.UIMaster.filterBooks, com.example.mybookshelf.MainActivity.saveBook.
int com.example.mybookshelf.dataClass.Book.getId()
Returns the unique identifier of the object.
References com.example.mybookshelf.dataClass.Book.id.
Referenced by com.example.mybookshelf.LayoutManager.CostumeListAdapter.bindBookData, com.example.mybookshelf.UIMaster.createBookBox, com.example.mybookshelf.LayoutManager.CostumeListAdapter.createTextWatcher, com.example.mybookshelf.DataBaseConnection.getRatingFromBook, com.example.mybookshelf.MainActivity.handleBookChange, com.example.mybookshelf.DataBaseConnection.removeBookFromUser.
boolean com.example.mybookshelf.dataClass.Book.isInDatabase()
Checks if the object is present in the database.
References com.example.mybookshelf.dataClass.Book.inDatabase.
Referenced by com.example.mybookshelf.dataClass.User.removeBook.
void com.example.mybookshelf.dataClass.Book.setInDatabase(boolean inDatabase)
Sets whether the object is stored in the database.
References com.example.mybookshelf.dataClass.Book.inDatabase.
Referenced by com.example.mybookshelf.MainActivity.saveBook.
com.example.mybookshelf.dataClass.Book.Book(String name, String release_date, int pages, String author, String image_url, String description, int id, String genre, String Status)
References com.example.mybookshelf.dataClass.Book.author, com.example.mybookshelf.dataClass.Book.description, com.example.mybookshelf.dataClass.Book.genre, com.example.mybookshelf.dataClass.Book.id, com.example.mybookshelf.dataClass.Book.image_url, com.example.mybookshelf.dataClass.Book.name, com.example.mybookshelf.dataClass.Book.pages, com.example.mybookshelf.dataClass.Book.release_date.
com.example.mybookshelf.dataClass.Book.Book(String name, String release_date, int pages, String author, String image_url, String description, int id, String genre)
References com.example.mybookshelf.dataClass.Book.author, com.example.mybookshelf.dataClass.Book.description, com.example.mybookshelf.dataClass.Book.genre, com.example.mybookshelf.dataClass.Book.id, com.example.mybookshelf.dataClass.Book.image_url, com.example.mybookshelf.dataClass.Book.name, com.example.mybookshelf.dataClass.Book.pages, com.example.mybookshelf.dataClass.Book.release_date.
com.example.mybookshelf.dataClass.Book.Book(String name, String release_date, int pages, String author, String image_url, String description, String genre)
References com.example.mybookshelf.dataClass.Book.author, com.example.mybookshelf.dataClass.Book.description, com.example.mybookshelf.dataClass.Book.genre, com.example.mybookshelf.dataClass.Book.image_url, com.example.mybookshelf.dataClass.Book.name, com.example.mybookshelf.dataClass.Book.pages, com.example.mybookshelf.dataClass.Book.release_date.
com.example.mybookshelf.dataClass.Book.Book(String name, int pages)
References com.example.mybookshelf.dataClass.Book.name, com.example.mybookshelf.dataClass.Book.pages.
com.example.mybookshelf.dataClass.Book.Book(String name)
References com.example.mybookshelf.dataClass.Book.name.
String com.example.mybookshelf.dataClass.Book.getName()
Returns the name.
References com.example.mybookshelf.dataClass.Book.name.
Referenced by com.example.mybookshelf.dataClass.User.addBook, com.example.mybookshelf.LayoutManager.CostumeListAdapter.bindBookData, com.example.mybookshelf.UIMaster.createBookBox, com.example.mybookshelf.UIMaster.filterBooks, com.example.mybookshelf.GoalHandler.handleBookAdded, com.example.mybookshelf.GoalHandler.handleBookChange, com.example.mybookshelf.GoalHandler.handleBookRemoved, com.example.mybookshelf.UIMaster.navigateToDetails, com.example.mybookshelf.dataClass.User.removeBook, com.example.mybookshelf.MainActivity.saveBook.
String com.example.mybookshelf.dataClass.Book.getRelease_date()
Returns the release date of the item.
References com.example.mybookshelf.dataClass.Book.release_date.
Referenced by com.example.mybookshelf.UIMaster.createBookBox.
int com.example.mybookshelf.dataClass.Book.getPages()
Returns the number of pages.
References com.example.mybookshelf.dataClass.Book.pages.
Referenced by com.example.mybookshelf.GoalHandler.handleBookAdded, com.example.mybookshelf.GoalHandler.handleBookChange, com.example.mybookshelf.GoalHandler.handleBookRemoved, com.example.mybookshelf.MainActivity.saveBook.
String com.example.mybookshelf.dataClass.Book.getAuthor()
Returns the author of the book.
References com.example.mybookshelf.dataClass.Book.author.
Referenced by com.example.mybookshelf.LayoutManager.CostumeListAdapter.bindBookData, com.example.mybookshelf.UIMaster.createBookBox, com.example.mybookshelf.UIMaster.filterBooks, com.example.mybookshelf.MainActivity.saveBook.
String com.example.mybookshelf.dataClass.Book.getImageUrl()
Returns the URL of the image.
References com.example.mybookshelf.dataClass.Book.image_url.
Referenced by com.example.mybookshelf.LayoutManager.CostumeListAdapter.bindBookData, com.example.mybookshelf.UIMaster.createBookBox, com.example.mybookshelf.MainActivity.saveBook.
String com.example.mybookshelf.dataClass.Book.getDescription()
Returns the description.
References com.example.mybookshelf.dataClass.Book.description.
Referenced by com.example.mybookshelf.MainActivity.saveBook.
String com.example.mybookshelf.dataClass.Book.getReleaseDate()
Returns the release date of the product.
References com.example.mybookshelf.dataClass.Book.release_date.
Referenced by com.example.mybookshelf.MainActivity.saveBook.
void com.example.mybookshelf.dataClass.Book.setAuthor(String author)
Sets the author of the document.
References com.example.mybookshelf.dataClass.Book.author.
Referenced by com.example.mybookshelf.UIMaster.createBookBox.
void com.example.mybookshelf.dataClass.Book.setRelease_date(String release_date)
Sets the release date.
References com.example.mybookshelf.dataClass.Book.release_date.
Referenced by com.example.mybookshelf.UIMaster.createBookBox.
void com.example.mybookshelf.dataClass.Book.setStatus(String status)
Sets the status to the specified value.
References com.example.mybookshelf.dataClass.Book.status.
Referenced by com.example.mybookshelf.MainActivity.saveBook.
String com.example.mybookshelf.dataClass.Book.getStatus()
Returns the current status.
References com.example.mybookshelf.dataClass.Book.status.
Referenced by com.example.mybookshelf.GoalHandler.handleBookAdded, com.example.mybookshelf.GoalHandler.handleBookChange, com.example.mybookshelf.MainActivity.handleBookChange, com.example.mybookshelf.UIMaster.navigateToDetails.