com::example::mybookshelf::BookRecommendationFlow
MainActivity com.example.mybookshelf.BookRecommendationFlow.mainActivity
Referenced by com.example.mybookshelf.BookRecommendationFlow.addChatMessage, com.example.mybookshelf.BookRecommendationFlow.BookRecommendationFlow, com.example.mybookshelf.BookRecommendationFlow.callAI, com.example.mybookshelf.BookRecommendationFlow.createStyledGridButton, com.example.mybookshelf.BookRecommendationFlow.handleAI, com.example.mybookshelf.BookRecommendationFlow.handleNo, com.example.mybookshelf.BookRecommendationFlow.hideThinkingAnimation, com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep1, com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep2, com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep3, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep1, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep2, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep3, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep4, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep5, com.example.mybookshelf.BookRecommendationFlow.showThinkingAnimation.
UIMaster com.example.mybookshelf.BookRecommendationFlow.uiMaster
Referenced by com.example.mybookshelf.BookRecommendationFlow.BookRecommendationFlow.
RelativeLayout com.example.mybookshelf.BookRecommendationFlow.box
Referenced by com.example.mybookshelf.BookRecommendationFlow.callAI, com.example.mybookshelf.BookRecommendationFlow.handleAI, com.example.mybookshelf.BookRecommendationFlow.handleNo, com.example.mybookshelf.BookRecommendationFlow.hideThinkingAnimation, com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep1, com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep2, com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep3, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep1, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep2, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep3, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep4, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep5, com.example.mybookshelf.BookRecommendationFlow.showThinkingAnimation.
ArrayList<String> com.example.mybookshelf.BookRecommendationFlow.atributes
Referenced by com.example.mybookshelf.BookRecommendationFlow.BookRecommendationFlow, com.example.mybookshelf.BookRecommendationFlow.buildAIStringBased, com.example.mybookshelf.BookRecommendationFlow.buildAIStringFresh, com.example.mybookshelf.BookRecommendationFlow.handleAI, com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep2, com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep3, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep2, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep3, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep4, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep5.
AiAPI com.example.mybookshelf.BookRecommendationFlow.ai
Referenced by com.example.mybookshelf.BookRecommendationFlow.BookRecommendationFlow.
String com.example.mybookshelf.BookRecommendationFlow.bookName
Referenced by com.example.mybookshelf.BookRecommendationFlow.BookRecommendationFlow, com.example.mybookshelf.BookRecommendationFlow.buildAIStringBased.
HashSet<String> com.example.mybookshelf.BookRecommendationFlow.doNotRecommend
Referenced by com.example.mybookshelf.BookRecommendationFlow.BookRecommendationFlow, com.example.mybookshelf.BookRecommendationFlow.buildAIStringFresh, com.example.mybookshelf.BookRecommendationFlow.callAI.
RelativeLayout com.example.mybookshelf.BookRecommendationFlow.loadingLayout
Referenced by com.example.mybookshelf.BookRecommendationFlow.showThinkingAnimation.
List<View> com.example.mybookshelf.BookRecommendationFlow.balls
Referenced by com.example.mybookshelf.BookRecommendationFlow.hideThinkingAnimation, com.example.mybookshelf.BookRecommendationFlow.showThinkingAnimation.
boolean com.example.mybookshelf.BookRecommendationFlow.isThinking
Referenced by com.example.mybookshelf.BookRecommendationFlow.hideThinkingAnimation, com.example.mybookshelf.BookRecommendationFlow.showThinkingAnimation.
com.example.mybookshelf.BookRecommendationFlow.BookRecommendationFlow(MainActivity mainActivity, UIMaster uiMaster, String bookName)
References com.example.mybookshelf.BookRecommendationFlow.ai, com.example.mybookshelf.BookRecommendationFlow.atributes, com.example.mybookshelf.BookRecommendationFlow.bookName, com.example.mybookshelf.BookRecommendationFlow.doNotRecommend, com.example.mybookshelf.BookRecommendationFlow.mainActivity, com.example.mybookshelf.BookRecommendationFlow.uiMaster.
void com.example.mybookshelf.BookRecommendationFlow.handleAI(String pathType)
Handles AI logic based on the path type and updates the UI accordingly.
References com.example.mybookshelf.BookRecommendationFlow.atributes, com.example.mybookshelf.BookRecommendationFlow.box, com.example.mybookshelf.BookRecommendationFlow.mainActivity, com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep1, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep1.
Referenced by com.example.mybookshelf.BookRecommendationFlow.handleNo.
void com.example.mybookshelf.BookRecommendationFlow.addChatMessage(String text, String senderType)
Adds a chat message to the UI based on the provided text and sender type. The method creates a TextView for the message, sets its properties such as color, background, and layout, and adds it to the GridLayout in the main activity. It also ensures that the ScrollView scrolls to show the latest message. text The text content of the chat message. senderType The type of the sender, either "user" or another identifier for system messages.
References com.example.mybookshelf.BookRecommendationFlow.mainActivity.
Referenced by com.example.mybookshelf.BookRecommendationFlow.callAI, com.example.mybookshelf.BookRecommendationFlow.handleNo, com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep1, com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep2, com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep3, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep1, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep2, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep3, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep4, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep5.
void com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep1()
Displays buttons for user to choose aspects of a book they liked most.
References com.example.mybookshelf.BookRecommendationFlow.addChatMessage, com.example.mybookshelf.BookRecommendationFlow.box, com.example.mybookshelf.BookRecommendationFlow.createStyledGridButton, com.example.mybookshelf.BookRecommendationFlow.mainActivity, com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep2.
Referenced by com.example.mybookshelf.BookRecommendationFlow.handleAI.
void com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep2(String selectedOption)
Displays a grid of buttons to choose book genre preferences and navigates to step 3 based on selection.
References com.example.mybookshelf.BookRecommendationFlow.addChatMessage, com.example.mybookshelf.BookRecommendationFlow.atributes, com.example.mybookshelf.BookRecommendationFlow.box, com.example.mybookshelf.BookRecommendationFlow.createStyledGridButton, com.example.mybookshelf.BookRecommendationFlow.mainActivity, com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep3.
Referenced by com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep1.
void com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep3(String selectedOption)
Displays a grid of buttons to select book attributes based on user input.
References com.example.mybookshelf.BookRecommendationFlow.addChatMessage, com.example.mybookshelf.BookRecommendationFlow.atributes, com.example.mybookshelf.BookRecommendationFlow.box, com.example.mybookshelf.BookRecommendationFlow.buildAIStringBased, com.example.mybookshelf.BookRecommendationFlow.createStyledGridButton, com.example.mybookshelf.BookRecommendationFlow.mainActivity.
Referenced by com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep2.
void com.example.mybookshelf.BookRecommendationFlow.buildAIStringBased(String selectedOption)
Builds a prompt based on selected attributes and calls the AI to generate a recommendation.
References com.example.mybookshelf.BookRecommendationFlow.atributes, com.example.mybookshelf.BookRecommendationFlow.bookName, com.example.mybookshelf.BookRecommendationFlow.callAI.
Referenced by com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep3.
void com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep1()
Displays a grid of buttons with book genres and handles user selection.
References com.example.mybookshelf.BookRecommendationFlow.addChatMessage, com.example.mybookshelf.BookRecommendationFlow.box, com.example.mybookshelf.BookRecommendationFlow.createStyledGridButton, com.example.mybookshelf.BookRecommendationFlow.mainActivity, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep2.
Referenced by com.example.mybookshelf.BookRecommendationFlow.handleAI.
void com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep2(String selectedOption)
Displays a step in the fresh start process with styled buttons.
References com.example.mybookshelf.BookRecommendationFlow.addChatMessage, com.example.mybookshelf.BookRecommendationFlow.atributes, com.example.mybookshelf.BookRecommendationFlow.box, com.example.mybookshelf.BookRecommendationFlow.createStyledGridButton, com.example.mybookshelf.BookRecommendationFlow.mainActivity, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep3.
Referenced by com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep1.
void com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep3(String selectedOption)
Displays a grid of buttons to select a setting.
References com.example.mybookshelf.BookRecommendationFlow.addChatMessage, com.example.mybookshelf.BookRecommendationFlow.atributes, com.example.mybookshelf.BookRecommendationFlow.box, com.example.mybookshelf.BookRecommendationFlow.createStyledGridButton, com.example.mybookshelf.BookRecommendationFlow.mainActivity, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep4.
Referenced by com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep2.
void com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep4(String selectedOption)
Displays step 4 of the fresh start process with character type selection options.
References com.example.mybookshelf.BookRecommendationFlow.addChatMessage, com.example.mybookshelf.BookRecommendationFlow.atributes, com.example.mybookshelf.BookRecommendationFlow.box, com.example.mybookshelf.BookRecommendationFlow.createStyledGridButton, com.example.mybookshelf.BookRecommendationFlow.mainActivity, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep5.
Referenced by com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep3.
void com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep5(String selectedOption)
Displays a grid of buttons for selecting story endings and updates chat messages accordingly.
References com.example.mybookshelf.BookRecommendationFlow.addChatMessage, com.example.mybookshelf.BookRecommendationFlow.atributes, com.example.mybookshelf.BookRecommendationFlow.box, com.example.mybookshelf.BookRecommendationFlow.buildAIStringFresh, com.example.mybookshelf.BookRecommendationFlow.createStyledGridButton, com.example.mybookshelf.BookRecommendationFlow.mainActivity.
Referenced by com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep4.
void com.example.mybookshelf.BookRecommendationFlow.buildAIStringFresh(String selectedOption)
Builds a prompt string based on selected attributes and calls the AI to fetch a book recommendation.
References com.example.mybookshelf.BookRecommendationFlow.atributes, com.example.mybookshelf.BookRecommendationFlow.callAI, com.example.mybookshelf.BookRecommendationFlow.doNotRecommend.
Referenced by com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep5.
void com.example.mybookshelf.BookRecommendationFlow.callAI(String prompt)
Initiates an AI request based on the given prompt and processes the response.
References com.example.mybookshelf.BookRecommendationFlow.addChatMessage, com.example.mybookshelf.BookRecommendationFlow.box, com.example.mybookshelf.BookRecommendationFlow.callAI, com.example.mybookshelf.BookRecommendationFlow.createStyledGridButton, com.example.mybookshelf.BookRecommendationFlow.doNotRecommend, com.example.mybookshelf.apis.AiAPI.fetchResponse, com.example.mybookshelf.BookRecommendationFlow.handleNo, com.example.mybookshelf.BookRecommendationFlow.hideThinkingAnimation, com.example.mybookshelf.BookRecommendationFlow.mainActivity, com.example.mybookshelf.BookRecommendationFlow.showThinkingAnimation.
Referenced by com.example.mybookshelf.BookRecommendationFlow.buildAIStringBased, com.example.mybookshelf.BookRecommendationFlow.buildAIStringFresh, com.example.mybookshelf.BookRecommendationFlow.callAI.
Button com.example.mybookshelf.BookRecommendationFlow.createStyledGridButton(String text, View.OnClickListener listener)
Creates a styled button with specified text and click listener for use in a grid layout.
References com.example.mybookshelf.BookRecommendationFlow.mainActivity.
Referenced by com.example.mybookshelf.BookRecommendationFlow.callAI, com.example.mybookshelf.BookRecommendationFlow.handleNo, com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep1, com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep2, com.example.mybookshelf.BookRecommendationFlow.showBookBasedStep3, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep1, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep2, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep3, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep4, com.example.mybookshelf.BookRecommendationFlow.showFreshStartStep5.
void com.example.mybookshelf.BookRecommendationFlow.handleNo()
Handles user response to a question by removing previous views, adding chat messages, and displaying a grid of options for further interaction.
References com.example.mybookshelf.BookRecommendationFlow.addChatMessage, com.example.mybookshelf.BookRecommendationFlow.box, com.example.mybookshelf.BookRecommendationFlow.createStyledGridButton, com.example.mybookshelf.BookRecommendationFlow.handleAI, com.example.mybookshelf.BookRecommendationFlow.mainActivity.
Referenced by com.example.mybookshelf.BookRecommendationFlow.callAI.
void com.example.mybookshelf.BookRecommendationFlow.showThinkingAnimation()
Displays a thinking animation with three bouncing balls in a RelativeLayout.
References com.example.mybookshelf.BookRecommendationFlow.balls, com.example.mybookshelf.BookRecommendationFlow.box, com.example.mybookshelf.BookRecommendationFlow.isThinking, com.example.mybookshelf.BookRecommendationFlow.loadingLayout, com.example.mybookshelf.BookRecommendationFlow.mainActivity.
Referenced by com.example.mybookshelf.BookRecommendationFlow.callAI.
void com.example.mybookshelf.BookRecommendationFlow.hideThinkingAnimation()
Hides the thinking animation by clearing animations and resetting views.
References com.example.mybookshelf.BookRecommendationFlow.balls, com.example.mybookshelf.BookRecommendationFlow.box, com.example.mybookshelf.BookRecommendationFlow.isThinking, com.example.mybookshelf.BookRecommendationFlow.mainActivity.
Referenced by com.example.mybookshelf.BookRecommendationFlow.callAI.