com::example::mybookshelf::dataClass::User
String com.example.mybookshelf.dataClass.User.user
Referenced by com.example.mybookshelf.dataClass.User.getUser, com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User.
String com.example.mybookshelf.dataClass.User.hash_password
Referenced by com.example.mybookshelf.dataClass.User.getPassword, com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User.
String com.example.mybookshelf.dataClass.User.email
int com.example.mybookshelf.dataClass.User.UID
Referenced by com.example.mybookshelf.dataClass.User.getUid, com.example.mybookshelf.dataClass.User.setUID, com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User.
LinkedList<Book> com.example.mybookshelf.dataClass.User.bookList
Referenced by com.example.mybookshelf.dataClass.User.addBook, com.example.mybookshelf.dataClass.User.getAuthors, com.example.mybookshelf.dataClass.User.getBookList, com.example.mybookshelf.dataClass.User.getGenres, com.example.mybookshelf.dataClass.User.removeBook, com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User.
TreeSet<String> com.example.mybookshelf.dataClass.User.authorList
Referenced by com.example.mybookshelf.dataClass.User.getAuthors, com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User.
LinkedList<Goal> com.example.mybookshelf.dataClass.User.goalList
Referenced by com.example.mybookshelf.dataClass.User.addGoal, com.example.mybookshelf.dataClass.User.getGoalList, com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User.
LinkedList<Goal> com.example.mybookshelf.dataClass.User.completedGoalList
Referenced by com.example.mybookshelf.dataClass.User.getCompletedGoalList, com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User.
LinkedList<Goal> com.example.mybookshelf.dataClass.User.failedGoalList
Referenced by com.example.mybookshelf.dataClass.User.getFailedGoalList, com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User.
LinkedList<Notification> com.example.mybookshelf.dataClass.User.notificationList
Referenced by com.example.mybookshelf.dataClass.User.User.
TreeSet<String> com.example.mybookshelf.dataClass.User.genreList
Referenced by com.example.mybookshelf.dataClass.User.getGenres, com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User.
MainActivity com.example.mybookshelf.dataClass.User.mainActivity
Referenced by com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User.
DataBaseConnection com.example.mybookshelf.dataClass.User.db
Referenced by com.example.mybookshelf.dataClass.User.removeBook, com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User.
boolean com.example.mybookshelf.dataClass.User.reminder
Referenced by com.example.mybookshelf.dataClass.User.isReminder, com.example.mybookshelf.dataClass.User.setReminder, com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User.
int com.example.mybookshelf.dataClass.User.hour
Referenced by com.example.mybookshelf.dataClass.User.getHour, com.example.mybookshelf.dataClass.User.setHour, com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User.
int com.example.mybookshelf.dataClass.User.minute
Referenced by com.example.mybookshelf.dataClass.User.getMinute, com.example.mybookshelf.dataClass.User.setMinute, com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User.
com.example.mybookshelf.dataClass.User.User(String user, String hash_password, int UID, DataBaseConnection db, boolean reminder, int hour, int minute, MainActivity mainActivity)
References com.example.mybookshelf.dataClass.User.authorList, com.example.mybookshelf.dataClass.User.bookList, com.example.mybookshelf.notifications.NotificationScheduler.cancelDailyNotification, com.example.mybookshelf.notifications.NotificationScheduler.cancelOneTimeNotification, com.example.mybookshelf.dataClass.User.completedGoalList, com.example.mybookshelf.dataClass.User.db, com.example.mybookshelf.dataClass.User.failedGoalList, com.example.mybookshelf.dataClass.User.genreList, com.example.mybookshelf.dataClass.User.goalList, com.example.mybookshelf.dataClass.User.hash_password, com.example.mybookshelf.dataClass.User.hour, com.example.mybookshelf.notifications.NotificationScheduler.isOneTimeNotificationScheduled, com.example.mybookshelf.dataClass.User.mainActivity, com.example.mybookshelf.dataClass.User.minute, com.example.mybookshelf.dataClass.User.reminder, com.example.mybookshelf.notifications.NotificationScheduler.scheduleOneTimeNotification, com.example.mybookshelf.dataClass.User.UID, com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.user.
Referenced by com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User.
com.example.mybookshelf.dataClass.User.User(String user, int UID, DataBaseConnection db, boolean reminder, int hour, int minute, MainActivity mainActivity)
References com.example.mybookshelf.dataClass.User.authorList, com.example.mybookshelf.dataClass.User.bookList, com.example.mybookshelf.notifications.NotificationScheduler.cancelOneTimeNotification, com.example.mybookshelf.dataClass.User.completedGoalList, com.example.mybookshelf.dataClass.User.db, com.example.mybookshelf.dataClass.User.failedGoalList, com.example.mybookshelf.dataClass.User.genreList, com.example.mybookshelf.dataClass.User.goalList, com.example.mybookshelf.dataClass.User.hash_password, com.example.mybookshelf.dataClass.User.hour, com.example.mybookshelf.notifications.NotificationScheduler.isOneTimeNotificationScheduled, com.example.mybookshelf.dataClass.User.mainActivity, com.example.mybookshelf.dataClass.User.minute, com.example.mybookshelf.dataClass.User.notificationList, com.example.mybookshelf.dataClass.User.reminder, com.example.mybookshelf.notifications.NotificationScheduler.scheduleOneTimeNotification, com.example.mybookshelf.dataClass.User.UID, com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.user.
com.example.mybookshelf.dataClass.User.User(String user, String hash_password)
References com.example.mybookshelf.dataClass.User.hash_password, com.example.mybookshelf.dataClass.User.user.
int com.example.mybookshelf.dataClass.User.getMinute()
Returns the current minute value.
References com.example.mybookshelf.dataClass.User.minute.
void com.example.mybookshelf.dataClass.User.setMinute(int minute)
Sets the minute value.
References com.example.mybookshelf.dataClass.User.minute.
int com.example.mybookshelf.dataClass.User.getHour()
Returns the current hour.
References com.example.mybookshelf.dataClass.User.hour.
void com.example.mybookshelf.dataClass.User.setHour(int hour)
Sets the hour value.
References com.example.mybookshelf.dataClass.User.hour.
boolean com.example.mybookshelf.dataClass.User.isReminder()
Checks if a reminder is set.
References com.example.mybookshelf.dataClass.User.reminder.
void com.example.mybookshelf.dataClass.User.setReminder(boolean reminder)
Sets the reminder flag to the specified value.
References com.example.mybookshelf.dataClass.User.reminder.
void com.example.mybookshelf.dataClass.User.setUID(int UID)
Sets the unique identifier (UID) of the object.
References com.example.mybookshelf.dataClass.User.UID.
String com.example.mybookshelf.dataClass.User.getUser()
Returns the current user.
References com.example.mybookshelf.dataClass.User.user.
Referenced by com.example.mybookshelf.Authenticator.checkLogin.
String com.example.mybookshelf.dataClass.User.getPassword()
Returns the hashed password.
References com.example.mybookshelf.dataClass.User.hash_password.
Referenced by com.example.mybookshelf.Authenticator.checkLogin.
List< Book > com.example.mybookshelf.dataClass.User.getBookList()
Returns the list of books.
References com.example.mybookshelf.dataClass.User.bookList.
void com.example.mybookshelf.dataClass.User.addBook(Book book, Context main)
Adds a book to the list if it is not already present.
References com.example.mybookshelf.dataClass.User.bookList, com.example.mybookshelf.dataClass.Book.getName.
void com.example.mybookshelf.dataClass.User.removeBook(Book book, Context main, RecyclerView container)
Removes a book from both the local list and the user interface. Iterates through the local book list to find and remove the specified book. Updates the UI by removing the corresponding visual representation of the book. If the book is marked as being in the database, attempts to remove it from there as well. Handles exceptions that may occur during database operations and provides user feedback. book the Book object representing the book to be removed main the Context object for UI operations container the RecyclerView container where the book's visual part is located
References com.example.mybookshelf.dataClass.User.bookList, com.example.mybookshelf.dataClass.User.db, com.example.mybookshelf.dataClass.Book.getName, com.example.mybookshelf.dataClass.User.getUid, com.example.mybookshelf.dataClass.Book.isInDatabase.
TreeSet< String > com.example.mybookshelf.dataClass.User.getAuthors()
Retrieves a set of authors from the list of books.
References com.example.mybookshelf.dataClass.User.authorList, com.example.mybookshelf.dataClass.User.bookList.
TreeSet< String > com.example.mybookshelf.dataClass.User.getGenres()
Retrieves a set of genres from the list of books.
References com.example.mybookshelf.dataClass.User.bookList, com.example.mybookshelf.dataClass.User.genreList.
int com.example.mybookshelf.dataClass.User.getUid()
Returns the unique identifier (UID).
References com.example.mybookshelf.dataClass.User.UID.
Referenced by com.example.mybookshelf.DataBaseConnection.addGoal, com.example.mybookshelf.DataBaseConnection.addNotification, com.example.mybookshelf.dataClass.User.removeBook.
LinkedList< Goal > com.example.mybookshelf.dataClass.User.getGoalList()
Returns the list of goals.
References com.example.mybookshelf.dataClass.User.goalList.
long com.example.mybookshelf.dataClass.User.addGoal(Goal goal)
Adds a goal to the list and returns its ID.
References com.example.mybookshelf.dataClass.Goal.getId, com.example.mybookshelf.dataClass.User.goalList.
LinkedList< Goal > com.example.mybookshelf.dataClass.User.getCompletedGoalList()
Returns the list of completed goals.
References com.example.mybookshelf.dataClass.User.completedGoalList.
void com.example.mybookshelf.dataClass.User.setUserName(String username)
Sets the user name.
List< Goal > com.example.mybookshelf.dataClass.User.getFailedGoalList()
Returns the list of failed goals.
References com.example.mybookshelf.dataClass.User.failedGoalList.