com::example::mybookshelf::notifications::NotificationScheduler
final String com.example.mybookshelf.notifications.NotificationScheduler.TAG
Referenced by com.example.mybookshelf.notifications.NotificationScheduler.cancelDailyNotification, com.example.mybookshelf.notifications.NotificationScheduler.cancelOneTimeNotification, com.example.mybookshelf.notifications.NotificationScheduler.changeDailyNotificationMessage, com.example.mybookshelf.notifications.NotificationScheduler.changeDailyNotificationTime, com.example.mybookshelf.notifications.NotificationScheduler.restoreNotifications, com.example.mybookshelf.notifications.NotificationScheduler.scheduleDailyNotification, com.example.mybookshelf.notifications.NotificationScheduler.scheduleOneTimeNotification.
final String com.example.mybookshelf.notifications.NotificationScheduler.PREFS_NAME
Referenced by com.example.mybookshelf.notifications.NotificationScheduler.cancelDailyNotification, com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationHour, com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationMessage, com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationMinute, com.example.mybookshelf.notifications.NotificationScheduler.isDailyNotificationActive, com.example.mybookshelf.notifications.NotificationScheduler.restoreNotifications, com.example.mybookshelf.notifications.NotificationScheduler.scheduleDailyNotification.
final String com.example.mybookshelf.notifications.NotificationScheduler.KEY_DAILY_ACTIVE
Referenced by com.example.mybookshelf.notifications.NotificationScheduler.cancelDailyNotification, com.example.mybookshelf.notifications.NotificationScheduler.isDailyNotificationActive, com.example.mybookshelf.notifications.NotificationScheduler.restoreNotifications, com.example.mybookshelf.notifications.NotificationScheduler.scheduleDailyNotification.
final String com.example.mybookshelf.notifications.NotificationScheduler.KEY_DAILY_HOUR
Referenced by com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationHour, com.example.mybookshelf.notifications.NotificationScheduler.restoreNotifications, com.example.mybookshelf.notifications.NotificationScheduler.scheduleDailyNotification.
final String com.example.mybookshelf.notifications.NotificationScheduler.KEY_DAILY_MINUTE
Referenced by com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationMinute, com.example.mybookshelf.notifications.NotificationScheduler.restoreNotifications, com.example.mybookshelf.notifications.NotificationScheduler.scheduleDailyNotification.
final String com.example.mybookshelf.notifications.NotificationScheduler.KEY_DAILY_MESSAGE
Referenced by com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationMessage, com.example.mybookshelf.notifications.NotificationScheduler.restoreNotifications, com.example.mybookshelf.notifications.NotificationScheduler.scheduleDailyNotification.
final int com.example.mybookshelf.notifications.NotificationScheduler.REQUEST_CODE_DAILY
Referenced by com.example.mybookshelf.notifications.NotificationScheduler.cancelDailyNotification, com.example.mybookshelf.notifications.NotificationScheduler.scheduleDailyNotification.
static void com.example.mybookshelf.notifications.NotificationScheduler.scheduleDailyNotification(Context context, int hour, int minute, String message)
Plant eine t├żgliche Notification zu einer bestimmten Uhrzeit
References com.example.mybookshelf.notifications.NotificationScheduler.KEY_DAILY_ACTIVE, com.example.mybookshelf.notifications.NotificationScheduler.KEY_DAILY_HOUR, com.example.mybookshelf.notifications.NotificationScheduler.KEY_DAILY_MESSAGE, com.example.mybookshelf.notifications.NotificationScheduler.KEY_DAILY_MINUTE, com.example.mybookshelf.notifications.NotificationScheduler.PREFS_NAME, com.example.mybookshelf.notifications.NotificationScheduler.REQUEST_CODE_DAILY, com.example.mybookshelf.notifications.NotificationScheduler.TAG.
Referenced by com.example.mybookshelf.notifications.NotificationScheduler.changeDailyNotificationMessage, com.example.mybookshelf.notifications.NotificationScheduler.changeDailyNotificationTime, com.example.mybookshelf.notifications.NotificationReceiver.onReceive, com.example.mybookshelf.notifications.NotificationScheduler.restoreNotifications, com.example.mybookshelf.notifications.NotificationScheduler.scheduleDailyNotification, com.example.mybookshelf.notifications.NotificationScheduler.toggleDailyNotification.
static void com.example.mybookshelf.notifications.NotificationScheduler.scheduleDailyNotification(Context context)
Schedules a daily notification at 8:00 PM with default message "Zeit zum Lesen!".
References com.example.mybookshelf.notifications.NotificationScheduler.scheduleDailyNotification.
static void com.example.mybookshelf.notifications.NotificationScheduler.changeDailyNotificationTime(Context context, int hour, int minute)
Changes the time of the daily notification.
References com.example.mybookshelf.notifications.NotificationScheduler.cancelDailyNotification, com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationMessage, com.example.mybookshelf.notifications.NotificationScheduler.scheduleDailyNotification, com.example.mybookshelf.notifications.NotificationScheduler.TAG.
static void com.example.mybookshelf.notifications.NotificationScheduler.changeDailyNotificationMessage(Context context, String message)
Ćndert die Nachricht der tŖglichen Notification und aktualisiert den Zeitplan.
References com.example.mybookshelf.notifications.NotificationScheduler.cancelDailyNotification, com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationHour, com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationMinute, com.example.mybookshelf.notifications.NotificationScheduler.isDailyNotificationActive, com.example.mybookshelf.notifications.NotificationScheduler.scheduleDailyNotification, com.example.mybookshelf.notifications.NotificationScheduler.TAG.
static void com.example.mybookshelf.notifications.NotificationScheduler.cancelDailyNotification(Context context)
Cancels the daily notification and updates preferences.
References com.example.mybookshelf.notifications.NotificationScheduler.KEY_DAILY_ACTIVE, com.example.mybookshelf.notifications.NotificationScheduler.PREFS_NAME, com.example.mybookshelf.notifications.NotificationScheduler.REQUEST_CODE_DAILY, com.example.mybookshelf.notifications.NotificationScheduler.TAG.
Referenced by com.example.mybookshelf.notifications.NotificationScheduler.changeDailyNotificationMessage, com.example.mybookshelf.notifications.NotificationScheduler.changeDailyNotificationTime, com.example.mybookshelf.GoalHandler.handleBookRemoved, com.example.mybookshelf.notifications.NotificationScheduler.toggleDailyNotification, com.example.mybookshelf.dataClass.User.User.
static void com.example.mybookshelf.notifications.NotificationScheduler.toggleDailyNotification(Context context)
Toggles the daily notification on or off.
References com.example.mybookshelf.notifications.NotificationScheduler.cancelDailyNotification, com.example.mybookshelf.notifications.NotificationScheduler.isDailyNotificationActive, com.example.mybookshelf.notifications.NotificationScheduler.scheduleDailyNotification.
static void com.example.mybookshelf.notifications.NotificationScheduler.restoreNotifications(Context context)
Restores daily notifications based on saved preferences.
References com.example.mybookshelf.notifications.NotificationScheduler.KEY_DAILY_ACTIVE, com.example.mybookshelf.notifications.NotificationScheduler.KEY_DAILY_HOUR, com.example.mybookshelf.notifications.NotificationScheduler.KEY_DAILY_MESSAGE, com.example.mybookshelf.notifications.NotificationScheduler.KEY_DAILY_MINUTE, com.example.mybookshelf.notifications.NotificationScheduler.PREFS_NAME, com.example.mybookshelf.notifications.NotificationScheduler.scheduleDailyNotification, com.example.mybookshelf.notifications.NotificationScheduler.TAG.
Referenced by com.example.mybookshelf.notifications.BootCompletedReceiver.onReceive.
static boolean com.example.mybookshelf.notifications.NotificationScheduler.isDailyNotificationActive(Context context)
Checks if daily notifications are active.
References com.example.mybookshelf.notifications.NotificationScheduler.KEY_DAILY_ACTIVE, com.example.mybookshelf.notifications.NotificationScheduler.PREFS_NAME.
Referenced by com.example.mybookshelf.notifications.NotificationScheduler.changeDailyNotificationMessage, com.example.mybookshelf.UIMaster.navigateToSettings, com.example.mybookshelf.notifications.NotificationScheduler.toggleDailyNotification.
static int com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationHour(Context context)
Returns the hour of the daily notification from SharedPreferences.
References com.example.mybookshelf.notifications.NotificationScheduler.KEY_DAILY_HOUR, com.example.mybookshelf.notifications.NotificationScheduler.PREFS_NAME.
Referenced by com.example.mybookshelf.notifications.NotificationScheduler.changeDailyNotificationMessage, com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationTimeString, com.example.mybookshelf.UIMaster.navigateToSettings.
static int com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationMinute(Context context)
Retrieves the minute of the daily notification.
References com.example.mybookshelf.notifications.NotificationScheduler.KEY_DAILY_MINUTE, com.example.mybookshelf.notifications.NotificationScheduler.PREFS_NAME.
Referenced by com.example.mybookshelf.notifications.NotificationScheduler.changeDailyNotificationMessage, com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationTimeString, com.example.mybookshelf.UIMaster.navigateToSettings.
static String com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationMessage(Context context)
Retrieves the daily notification message from SharedPreferences.
References com.example.mybookshelf.notifications.NotificationScheduler.KEY_DAILY_MESSAGE, com.example.mybookshelf.notifications.NotificationScheduler.PREFS_NAME.
Referenced by com.example.mybookshelf.notifications.NotificationScheduler.changeDailyNotificationTime.
static String com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationTimeString(Context context)
Returns the formatted daily notification time string.
References com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationHour, com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationMinute.
static void com.example.mybookshelf.notifications.NotificationScheduler.sendGoalCompletedNotification(Context context, Goal goal)
/** Sends a notification when a goal is completed.
References com.example.mybookshelf.notifications.NotificationChannelManager.DEFAULT_CHANNEL_ID, com.example.mybookshelf.dataClass.Goal.getGoal.
static void com.example.mybookshelf.notifications.NotificationScheduler.scheduleOneTimeNotification(Context context, LocalDateTime dateTime, int requestCode)
Schedules a one-time notification at a specified date and time. This method sets up an alarm to trigger a notification at the given LocalDateTime. It checks if the provided date and time is in the past, logs a warning, and returns early if true. Otherwise, it creates an Intent with necessary extras and uses PendingIntent to schedule the notification using AlarmManager. The method also handles permission checks for scheduling exact alarms on newer Android versions.
References com.example.mybookshelf.notifications.NotificationScheduler.TAG.
Referenced by com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User.
static void com.example.mybookshelf.notifications.NotificationScheduler.cancelOneTimeNotification(Context context, int requestCode)
Cancels a one-time scheduled notification using the provided request code.
References com.example.mybookshelf.notifications.NotificationScheduler.TAG.
Referenced by com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User.
static boolean com.example.mybookshelf.notifications.NotificationScheduler.isOneTimeNotificationScheduled(Context context, int requestCode)
Checks if a one-time notification is scheduled.
Referenced by com.example.mybookshelf.dataClass.User.User, com.example.mybookshelf.dataClass.User.User.