com::example::mybookshelf::DataBaseConnection
final ExecutorService com.example.mybookshelf.DataBaseConnection.executorService
Referenced by com.example.mybookshelf.DataBaseConnection.addBookToUser, com.example.mybookshelf.DataBaseConnection.addGoal, com.example.mybookshelf.DataBaseConnection.addNotification, com.example.mybookshelf.DataBaseConnection.addUser, com.example.mybookshelf.DataBaseConnection.changeEmail, com.example.mybookshelf.DataBaseConnection.changePassword, com.example.mybookshelf.DataBaseConnection.changeUserName, com.example.mybookshelf.DataBaseConnection.checkLogin, com.example.mybookshelf.DataBaseConnection.checkPassword, com.example.mybookshelf.DataBaseConnection.deleteUser, com.example.mybookshelf.DataBaseConnection.getAllGoalsForUser, com.example.mybookshelf.DataBaseConnection.getAllNotificationsForUser, com.example.mybookshelf.DataBaseConnection.getBookByName, com.example.mybookshelf.DataBaseConnection.getBooksFromUID, com.example.mybookshelf.DataBaseConnection.getNotesFromUser, com.example.mybookshelf.DataBaseConnection.getRatingFromBook, com.example.mybookshelf.DataBaseConnection.getReadingTimeByMonth, com.example.mybookshelf.DataBaseConnection.getTime, com.example.mybookshelf.DataBaseConnection.getToken, com.example.mybookshelf.DataBaseConnection.initialize, com.example.mybookshelf.DataBaseConnection.notesChanged, com.example.mybookshelf.DataBaseConnection.removeBookFromUser, com.example.mybookshelf.DataBaseConnection.removeGoal, com.example.mybookshelf.DataBaseConnection.removeNotification, com.example.mybookshelf.DataBaseConnection.updateGoalProgress, com.example.mybookshelf.DataBaseConnection.updateReadingStatus.
String com.example.mybookshelf.DataBaseConnection.URL
Referenced by com.example.mybookshelf.DataBaseConnection.addBookToUser, com.example.mybookshelf.DataBaseConnection.addGoal, com.example.mybookshelf.DataBaseConnection.addNewBook, com.example.mybookshelf.DataBaseConnection.addNotification, com.example.mybookshelf.DataBaseConnection.addUser, com.example.mybookshelf.DataBaseConnection.changeEmail, com.example.mybookshelf.DataBaseConnection.changePassword, com.example.mybookshelf.DataBaseConnection.changeUserName, com.example.mybookshelf.DataBaseConnection.checkLogin, com.example.mybookshelf.DataBaseConnection.checkPassword, com.example.mybookshelf.DataBaseConnection.deleteUser, com.example.mybookshelf.DataBaseConnection.getAllGoalsForUser, com.example.mybookshelf.DataBaseConnection.getAllNotificationsForUser, com.example.mybookshelf.DataBaseConnection.getBookByName, com.example.mybookshelf.DataBaseConnection.getBooksFromUID, com.example.mybookshelf.DataBaseConnection.getNotesFromUser, com.example.mybookshelf.DataBaseConnection.getRatingFromBook, com.example.mybookshelf.DataBaseConnection.getReadingTimeByMonth, com.example.mybookshelf.DataBaseConnection.getTime, com.example.mybookshelf.DataBaseConnection.getToken, com.example.mybookshelf.DataBaseConnection.initialize, com.example.mybookshelf.DataBaseConnection.notesChanged, com.example.mybookshelf.DataBaseConnection.removeBookFromUser, com.example.mybookshelf.DataBaseConnection.removeGoal, com.example.mybookshelf.DataBaseConnection.removeNotification, com.example.mybookshelf.DataBaseConnection.setTime, com.example.mybookshelf.DataBaseConnection.updateGoalProgress, com.example.mybookshelf.DataBaseConnection.updateReadingStatus.
final MainActivity com.example.mybookshelf.DataBaseConnection.context
Referenced by com.example.mybookshelf.DataBaseConnection.addUser, com.example.mybookshelf.DataBaseConnection.DataBaseConnection, com.example.mybookshelf.DataBaseConnection.initialize, com.example.mybookshelf.DataBaseConnection.loadTrustStore.
File com.example.mybookshelf.DataBaseConnection.trustStoreFile
Referenced by com.example.mybookshelf.DataBaseConnection.initialize.
final String com.example.mybookshelf.DataBaseConnection.USER
Referenced by com.example.mybookshelf.DataBaseConnection.addBookToUser, com.example.mybookshelf.DataBaseConnection.addGoal, com.example.mybookshelf.DataBaseConnection.addNewBook, com.example.mybookshelf.DataBaseConnection.addNotification, com.example.mybookshelf.DataBaseConnection.addUser, com.example.mybookshelf.DataBaseConnection.changeEmail, com.example.mybookshelf.DataBaseConnection.changePassword, com.example.mybookshelf.DataBaseConnection.changeUserName, com.example.mybookshelf.DataBaseConnection.checkLogin, com.example.mybookshelf.DataBaseConnection.checkPassword, com.example.mybookshelf.DataBaseConnection.deleteUser, com.example.mybookshelf.DataBaseConnection.getAllGoalsForUser, com.example.mybookshelf.DataBaseConnection.getAllNotificationsForUser, com.example.mybookshelf.DataBaseConnection.getBookByName, com.example.mybookshelf.DataBaseConnection.getBooksFromUID, com.example.mybookshelf.DataBaseConnection.getNotesFromUser, com.example.mybookshelf.DataBaseConnection.getRatingFromBook, com.example.mybookshelf.DataBaseConnection.getReadingTimeByMonth, com.example.mybookshelf.DataBaseConnection.getTime, com.example.mybookshelf.DataBaseConnection.getToken, com.example.mybookshelf.DataBaseConnection.initialize, com.example.mybookshelf.DataBaseConnection.notesChanged, com.example.mybookshelf.DataBaseConnection.removeBookFromUser, com.example.mybookshelf.DataBaseConnection.removeGoal, com.example.mybookshelf.DataBaseConnection.removeNotification, com.example.mybookshelf.DataBaseConnection.setTime, com.example.mybookshelf.DataBaseConnection.updateGoalProgress, com.example.mybookshelf.DataBaseConnection.updateReadingStatus.
final String com.example.mybookshelf.DataBaseConnection.PASSWORD
Referenced by com.example.mybookshelf.DataBaseConnection.addBookToUser, com.example.mybookshelf.DataBaseConnection.addGoal, com.example.mybookshelf.DataBaseConnection.addNewBook, com.example.mybookshelf.DataBaseConnection.addNotification, com.example.mybookshelf.DataBaseConnection.addUser, com.example.mybookshelf.DataBaseConnection.changeEmail, com.example.mybookshelf.DataBaseConnection.changePassword, com.example.mybookshelf.DataBaseConnection.changeUserName, com.example.mybookshelf.DataBaseConnection.checkLogin, com.example.mybookshelf.DataBaseConnection.checkPassword, com.example.mybookshelf.DataBaseConnection.deleteUser, com.example.mybookshelf.DataBaseConnection.getAllGoalsForUser, com.example.mybookshelf.DataBaseConnection.getAllNotificationsForUser, com.example.mybookshelf.DataBaseConnection.getBookByName, com.example.mybookshelf.DataBaseConnection.getBooksFromUID, com.example.mybookshelf.DataBaseConnection.getNotesFromUser, com.example.mybookshelf.DataBaseConnection.getRatingFromBook, com.example.mybookshelf.DataBaseConnection.getReadingTimeByMonth, com.example.mybookshelf.DataBaseConnection.getTime, com.example.mybookshelf.DataBaseConnection.getToken, com.example.mybookshelf.DataBaseConnection.initialize, com.example.mybookshelf.DataBaseConnection.notesChanged, com.example.mybookshelf.DataBaseConnection.removeBookFromUser, com.example.mybookshelf.DataBaseConnection.removeGoal, com.example.mybookshelf.DataBaseConnection.removeNotification, com.example.mybookshelf.DataBaseConnection.setTime, com.example.mybookshelf.DataBaseConnection.updateGoalProgress, com.example.mybookshelf.DataBaseConnection.updateReadingStatus.
com.example.mybookshelf.DataBaseConnection.DataBaseConnection(MainActivity context)
References com.example.mybookshelf.DataBaseConnection.context, com.example.mybookshelf.DataBaseConnection.initialize.
Future< Integer > com.example.mybookshelf.DataBaseConnection.checkLogin(String username, char[] password)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
Future< String > com.example.mybookshelf.DataBaseConnection.getToken(int uid)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
void com.example.mybookshelf.DataBaseConnection.addUser(String username, String email, String password)
References com.example.mybookshelf.DataBaseConnection.context, com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.generateSessionToken, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
String com.example.mybookshelf.DataBaseConnection.generateSessionToken()
Referenced by com.example.mybookshelf.DataBaseConnection.addUser.
Future< List< Book > > com.example.mybookshelf.DataBaseConnection.getBooksFromUID(int uid)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
Future< Book > com.example.mybookshelf.DataBaseConnection.getBookByName(String bookName)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
void com.example.mybookshelf.DataBaseConnection.addBookToUser(int userId, String status, String score, LocalDate finished, String bookName, String author, int pages, String releaseDate, String imageUrl, String description, double readingTime, String genre)
References com.example.mybookshelf.DataBaseConnection.addNewBook, com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
Future< Float > com.example.mybookshelf.DataBaseConnection.getRatingFromBook(Book book)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.dataClass.Book.getId, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
Future< ArrayList< BarEntry > > com.example.mybookshelf.DataBaseConnection.getReadingTimeByMonth(int UID)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
void com.example.mybookshelf.DataBaseConnection.removeBookFromUser(Book book, int UID)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.dataClass.Book.getId, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
void com.example.mybookshelf.DataBaseConnection.notesChanged(int UID, int bookID, String note)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
Future< String > com.example.mybookshelf.DataBaseConnection.getNotesFromUser(int UID, int bookID)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
void com.example.mybookshelf.DataBaseConnection.addNotification(User user, String message)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.dataClass.User.getUid, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
void com.example.mybookshelf.DataBaseConnection.removeNotification(int notificationId, int userId)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
void com.example.mybookshelf.DataBaseConnection.getAllNotificationsForUser(int userId, Consumer< List< Notification > > callback)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
long com.example.mybookshelf.DataBaseConnection.addGoal(Goal goal, User user)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.dataClass.Goal.getBookName, com.example.mybookshelf.dataClass.Goal.getFrequenzy, com.example.mybookshelf.dataClass.Goal.getGoal, com.example.mybookshelf.dataClass.Goal.getProgress, com.example.mybookshelf.dataClass.Goal.getTarget, com.example.mybookshelf.dataClass.User.getUid, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
void com.example.mybookshelf.DataBaseConnection.removeGoal(int goalId, int userId)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
void com.example.mybookshelf.DataBaseConnection.getAllGoalsForUser(int userId, Consumer< List< Goal > > callback)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.dataClass.Goal.setId, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
void com.example.mybookshelf.DataBaseConnection.deleteUser(int userId)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
Future< String > com.example.mybookshelf.DataBaseConnection.checkPassword(int userId)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
void com.example.mybookshelf.DataBaseConnection.changePassword(int userId, String newPassword)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
void com.example.mybookshelf.DataBaseConnection.changeUserName(int userId, String newUser)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
void com.example.mybookshelf.DataBaseConnection.changeEmail(int userId, String email)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
Future< LocalTime > com.example.mybookshelf.DataBaseConnection.getTime(int userId)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
void com.example.mybookshelf.DataBaseConnection.setTime(int userId, LocalTime time)
References com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
void com.example.mybookshelf.DataBaseConnection.updateReadingStatus(int userId, int bookId, String readingStatus)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
void com.example.mybookshelf.DataBaseConnection.updateGoalProgress(int userId, int goalID, int progress)
References com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
void com.example.mybookshelf.DataBaseConnection.initialize()
References com.example.mybookshelf.DataBaseConnection.context, com.example.mybookshelf.DataBaseConnection.executorService, com.example.mybookshelf.DataBaseConnection.loadTrustStore, com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.trustStoreFile, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
Referenced by com.example.mybookshelf.DataBaseConnection.DataBaseConnection.
KeyStore com.example.mybookshelf.DataBaseConnection.loadTrustStore()
References com.example.mybookshelf.DataBaseConnection.context.
Referenced by com.example.mybookshelf.DataBaseConnection.initialize.
int com.example.mybookshelf.DataBaseConnection.addNewBook(String bookName, String author, int pages, String releaseDate, String imageUrl, String description, String genre)
References com.example.mybookshelf.DataBaseConnection.PASSWORD, com.example.mybookshelf.DataBaseConnection.URL, com.example.mybookshelf.DataBaseConnection.USER.
Referenced by com.example.mybookshelf.DataBaseConnection.addBookToUser.