com::example::mybookshelf::UIMaster
MainActivity com.example.mybookshelf.UIMaster.mainActivity
List<Goal> com.example.mybookshelf.UIMaster.goalList
EditText com.example.mybookshelf.UIMaster.usernameEditText
Referenced by com.example.mybookshelf.UIMaster.showLogin, com.example.mybookshelf.UIMaster.showRegister.
EditText com.example.mybookshelf.UIMaster.passwordEditText
Referenced by com.example.mybookshelf.UIMaster.showLogin, com.example.mybookshelf.UIMaster.showRegister.
EditText com.example.mybookshelf.UIMaster.emailEditText
Referenced by com.example.mybookshelf.UIMaster.showRegister.
EditText com.example.mybookshelf.UIMaster.repeatPassword
Referenced by com.example.mybookshelf.UIMaster.showRegister.
Button com.example.mybookshelf.UIMaster.loginButton
Referenced by com.example.mybookshelf.UIMaster.showLogin.
Button com.example.mybookshelf.UIMaster.registerButton
Referenced by com.example.mybookshelf.UIMaster.showRegister.
Button com.example.mybookshelf.UIMaster.switchToLoginButton
Referenced by com.example.mybookshelf.UIMaster.showRegister.
Button com.example.mybookshelf.UIMaster.switchToRegisterButton
Referenced by com.example.mybookshelf.UIMaster.showLogin.
int com.example.mybookshelf.UIMaster.timeSpentReading
Referenced by com.example.mybookshelf.UIMaster.reduceTimeSpendReading, com.example.mybookshelf.UIMaster.updateReadingTime.
ImageButton com.example.mybookshelf.UIMaster.nav_searchBtn
Referenced by com.example.mybookshelf.UIMaster.navigateToDetails, com.example.mybookshelf.UIMaster.navigateToGoals, com.example.mybookshelf.UIMaster.navigateToSettings, com.example.mybookshelf.UIMaster.setupNavigationButtons, com.example.mybookshelf.UIMaster.setupNavigationListeners.
ImageButton com.example.mybookshelf.UIMaster.nav_StatsBtn
Referenced by com.example.mybookshelf.UIMaster.navigateToDetails, com.example.mybookshelf.UIMaster.navigateToGoals, com.example.mybookshelf.UIMaster.navigateToSettings, com.example.mybookshelf.UIMaster.setupNavigationButtons.
TextView com.example.mybookshelf.UIMaster.timeSpentReadingTextView
Referenced by com.example.mybookshelf.UIMaster.navigateToStartingPage, com.example.mybookshelf.UIMaster.reduceTimeSpendReading, com.example.mybookshelf.UIMaster.updateReadingTime.
BooksAPI com.example.mybookshelf.UIMaster.booksAPI
Referenced by com.example.mybookshelf.UIMaster.UIMaster.
AiAPI com.example.mybookshelf.UIMaster.ai
Referenced by com.example.mybookshelf.UIMaster.UIMaster.
DataBaseConnection com.example.mybookshelf.UIMaster.db
Referenced by com.example.mybookshelf.UIMaster.createBookBox, com.example.mybookshelf.UIMaster.loadChartDataAsync, com.example.mybookshelf.UIMaster.navigateToGoals, com.example.mybookshelf.UIMaster.navigateToStartingPage, com.example.mybookshelf.UIMaster.setDb, com.example.mybookshelf.UIMaster.UIMaster.
User com.example.mybookshelf.UIMaster.logedindUser
Referenced by com.example.mybookshelf.UIMaster.createBookBox, com.example.mybookshelf.UIMaster.fillSpinners, com.example.mybookshelf.UIMaster.navigateToGoals, com.example.mybookshelf.UIMaster.navigateToStartingPage.
Map<View, Book> com.example.mybookshelf.UIMaster.bookViewMap
Referenced by com.example.mybookshelf.UIMaster.createBookBox, com.example.mybookshelf.UIMaster.filterBooks, com.example.mybookshelf.UIMaster.UIMaster.
final ExecutorService com.example.mybookshelf.UIMaster.executorService
String com.example.mybookshelf.UIMaster.AIprompt
BookRecommendationFlow com.example.mybookshelf.UIMaster.brf
Referenced by com.example.mybookshelf.UIMaster.navigateToDetails.
CostumeListAdapter com.example.mybookshelf.UIMaster.listAdapter
Referenced by com.example.mybookshelf.UIMaster.navigateToStartingPage.
BarChart com.example.mybookshelf.UIMaster.barChart
Referenced by com.example.mybookshelf.UIMaster.configureAxes, com.example.mybookshelf.UIMaster.configureChart, com.example.mybookshelf.UIMaster.initializeViews, com.example.mybookshelf.UIMaster.setupChart.
com.example.mybookshelf.UIMaster.UIMaster(MainActivity main)
References com.example.mybookshelf.UIMaster.ai, com.example.mybookshelf.UIMaster.booksAPI, com.example.mybookshelf.UIMaster.bookViewMap, com.example.mybookshelf.UIMaster.db.
void com.example.mybookshelf.UIMaster.setUSer(User user)
Sets the logged-in user.
void com.example.mybookshelf.UIMaster.reduceTimeSpendReading(int time, TextView timeSpentReadingTextView)
Reduces the time spent reading by a given duration and updates the UI accordingly.
References com.example.mybookshelf.UIMaster.timeSpentReading, com.example.mybookshelf.UIMaster.timeSpentReadingTextView.
void com.example.mybookshelf.UIMaster.createBookBox(LinearLayout container, Book book, boolean isSearch)
Creates a visual representation of a book as a box within a given container.
References com.example.mybookshelf.UIMaster.bookViewMap, com.example.mybookshelf.UIMaster.db, com.example.mybookshelf.dataClass.Book.getAuthor, com.example.mybookshelf.UIMaster.getBtnAdd, com.example.mybookshelf.UIMaster.getBtnRemove, com.example.mybookshelf.dataClass.Book.getId, com.example.mybookshelf.dataClass.Book.getImageUrl, com.example.mybookshelf.dataClass.Book.getName, com.example.mybookshelf.dataClass.Book.getRelease_date, com.example.mybookshelf.UIMaster.logedindUser, com.example.mybookshelf.UIMaster.navigateToDetails, com.example.mybookshelf.dataClass.Book.setAuthor, com.example.mybookshelf.dataClass.Book.setRelease_date.
void com.example.mybookshelf.UIMaster.clearUI(LinearLayout container)
Clears all views from the given LinearLayout container.
void com.example.mybookshelf.UIMaster.updateReadingTime(int pages, TextView timeSpentReadingTextView)
Updates the reading time based on the number of pages read and displays it in the specified TextView.
References com.example.mybookshelf.UIMaster.timeSpentReading, com.example.mybookshelf.UIMaster.timeSpentReadingTextView.
void com.example.mybookshelf.UIMaster.showLogin()
Displays the login screen and handles user login attempts.
References com.example.mybookshelf.UIMaster.loginButton, com.example.mybookshelf.UIMaster.passwordEditText, com.example.mybookshelf.UIMaster.showRegister, com.example.mybookshelf.UIMaster.switchToRegisterButton, com.example.mybookshelf.UIMaster.usernameEditText.
Referenced by com.example.mybookshelf.UIMaster.navigateToSettings, com.example.mybookshelf.UIMaster.showRegister.
void com.example.mybookshelf.UIMaster.showRegister()
Displays the registration screen and sets up event listeners for user interactions. This method switches the main activity's content view to the registration layout, initializes UI components, and registers click listeners for the register button and the switch-to-login button. When the register button is clicked, it calls MainActivity#handleRegister(EditText, EditText, EditText, EditText) to process user input and register a new account. If an exception occurs during this process, it throws a runtime exception. Similarly, when the switch-to-login button is clicked, it attempts to show the login screen by calling showLogin(), handling exceptions in the same manner.
References com.example.mybookshelf.UIMaster.emailEditText, com.example.mybookshelf.UIMaster.passwordEditText, com.example.mybookshelf.UIMaster.registerButton, com.example.mybookshelf.UIMaster.repeatPassword, com.example.mybookshelf.UIMaster.showLogin, com.example.mybookshelf.UIMaster.switchToLoginButton, com.example.mybookshelf.UIMaster.usernameEditText.
Referenced by com.example.mybookshelf.UIMaster.showLogin.
void com.example.mybookshelf.UIMaster.navigateToStats()
Navigates to the stats page, initializes views, sets up navigation listeners, and loads chart data asynchronously.
References com.example.mybookshelf.UIMaster.initializeViews, com.example.mybookshelf.UIMaster.loadChartDataAsync, com.example.mybookshelf.UIMaster.setupNavigationListeners.
Referenced by com.example.mybookshelf.UIMaster.navigateToDetails, com.example.mybookshelf.UIMaster.navigateToGoals, com.example.mybookshelf.UIMaster.navigateToSettings, com.example.mybookshelf.UIMaster.setupNavigationButtons.
void com.example.mybookshelf.UIMaster.navigateToStartingPage()
Navigates to the starting page, updating the UI and loading user data in the background.
References com.example.mybookshelf.UIMaster.db, com.example.mybookshelf.UIMaster.listAdapter, com.example.mybookshelf.UIMaster.logedindUser, com.example.mybookshelf.UIMaster.setupNavigationButtons, com.example.mybookshelf.UIMaster.timeSpentReadingTextView.
Referenced by com.example.mybookshelf.UIMaster.navigateToDetails, com.example.mybookshelf.UIMaster.navigateToGoals, com.example.mybookshelf.UIMaster.navigateToSettings.
void com.example.mybookshelf.UIMaster.navigateToDetails(Book book)
Navigates to the details page of a selected book. This method sets up the UI for displaying detailed information about a book, including its title, author, description, number of pages, genre, and rating. It also handles user interactions such as navigating to other sections of the app, updating the reading status of the book, and initiating AI-based recommendations. book The Book object containing details about the book to be displayed.
References com.example.mybookshelf.UIMaster.brf, com.example.mybookshelf.dataClass.Book.getName, com.example.mybookshelf.dataClass.Book.getStatus, com.example.mybookshelf.UIMaster.nav_searchBtn, com.example.mybookshelf.UIMaster.nav_StatsBtn, com.example.mybookshelf.UIMaster.navigateToGoals, com.example.mybookshelf.UIMaster.navigateToSettings, com.example.mybookshelf.UIMaster.navigateToStartingPage, com.example.mybookshelf.UIMaster.navigateToStats.
Referenced by com.example.mybookshelf.UIMaster.createBookBox.
void com.example.mybookshelf.UIMaster.handleListSearch()
Handles the display and functionality of the list search interface, including animations and filtering books based on user input.
References com.example.mybookshelf.UIMaster.fillSpinners, com.example.mybookshelf.UIMaster.filterBooks.
Referenced by com.example.mybookshelf.UIMaster.setupNavigationButtons.
void com.example.mybookshelf.UIMaster.fillSpinners()
Fills spinners with authors and genres from the logged-in user, adding a default "All" option.
References com.example.mybookshelf.UIMaster.logedindUser.
Referenced by com.example.mybookshelf.UIMaster.handleListSearch.
void com.example.mybookshelf.UIMaster.navigateToGoals()
Navigates to and sets up the Goals screen, allowing users to view, add, and manage their reading goals. This method performs several key tasks: Sets the content view to the Goals activity layout. Initializes and configures a RecyclerView to display goal items. Adds click listeners for buttons that switch between displaying current, completed, and failed goals. Configures an AlertDialog with options to edit or delete selected goals. Handles adding new goals through user input, including validation of fields and database operations. mainActivity The MainActivity instance that calls this method, used for accessing resources, context, and user data.
References com.example.mybookshelf.UIMaster.db, com.example.mybookshelf.UIMaster.logedindUser, com.example.mybookshelf.UIMaster.nav_searchBtn, com.example.mybookshelf.UIMaster.nav_StatsBtn, com.example.mybookshelf.UIMaster.navigateToSettings, com.example.mybookshelf.UIMaster.navigateToStartingPage, com.example.mybookshelf.UIMaster.navigateToStats, com.example.mybookshelf.LayoutManager.CustomGoalAdapter.setGoals.
Referenced by com.example.mybookshelf.UIMaster.navigateToDetails, com.example.mybookshelf.UIMaster.navigateToSettings, com.example.mybookshelf.UIMaster.setupNavigationButtons.
void com.example.mybookshelf.UIMaster.navigateToSettings()
Navigates to the settings screen and sets up the UI elements and their corresponding listeners. This method is responsible for: Setting the content view to the main settings layout. Initializing various UI components such as buttons, text views, switches, and time pickers. Configuring listeners for UI events, including button clicks and changes in switch states. Handling user interactions for changing passwords, deleting accounts, changing usernames, changing emails, and configuring notification settings. ExecutionException if an error occurs during asynchronous execution. InterruptedException if the current thread is interrupted.
References com.example.mybookshelf.Authenticator.clearStoredToken, com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationHour, com.example.mybookshelf.notifications.NotificationScheduler.getDailyNotificationMinute, com.example.mybookshelf.notifications.NotificationScheduler.isDailyNotificationActive, com.example.mybookshelf.UIMaster.nav_searchBtn, com.example.mybookshelf.UIMaster.nav_StatsBtn, com.example.mybookshelf.UIMaster.navigateToGoals, com.example.mybookshelf.UIMaster.navigateToStartingPage, com.example.mybookshelf.UIMaster.navigateToStats, com.example.mybookshelf.UIMaster.showLogin.
Referenced by com.example.mybookshelf.UIMaster.navigateToDetails, com.example.mybookshelf.UIMaster.navigateToGoals, com.example.mybookshelf.UIMaster.setupNavigationButtons.
void com.example.mybookshelf.UIMaster.setDb(DataBaseConnection db)
Sets the database connection for this instance.
References com.example.mybookshelf.UIMaster.db.
ImageButton com.example.mybookshelf.UIMaster.getBtnAdd(Book book)
Creates and returns an ImageButton that, when clicked, calls saveBook with the given book.
Referenced by com.example.mybookshelf.UIMaster.createBookBox.
ImageButton com.example.mybookshelf.UIMaster.getBtnRemove(Book book)
Creates and configures an ImageButton to remove a specified book.
Referenced by com.example.mybookshelf.UIMaster.createBookBox.
void com.example.mybookshelf.UIMaster.initializeViews()
Initializes the bar chart view by finding it in the main activity layout.
References com.example.mybookshelf.UIMaster.barChart.
Referenced by com.example.mybookshelf.UIMaster.navigateToStats.
void com.example.mybookshelf.UIMaster.setupNavigationListeners()
Sets up click listeners for navigation buttons in the main activity. Each button is associated with a different navigation action: Home button navigates to the starting page. Search button triggers a search operation handled by the main activity. Goals button navigates to the goals page. Settings button navigates to the settings page.
References com.example.mybookshelf.UIMaster.nav_searchBtn.
Referenced by com.example.mybookshelf.UIMaster.navigateToStats.
void com.example.mybookshelf.UIMaster.loadChartDataAsync()
Asynchronously loads and displays chart data using AsyncTask.
References com.example.mybookshelf.UIMaster.db, com.example.mybookshelf.UIMaster.setupChart, com.example.mybookshelf.UIMaster.showErrorMessage.
Referenced by com.example.mybookshelf.UIMaster.navigateToStats.
void com.example.mybookshelf.UIMaster.setupChart(ChartData chartData)
Sets up the bar chart with reading time data in hours.
References com.example.mybookshelf.UIMaster.barChart, com.example.mybookshelf.UIMaster.configureAxes, com.example.mybookshelf.UIMaster.configureChart, com.example.mybookshelf.UIMaster.convertMinutesToHours, com.example.mybookshelf.UIMaster.displayTotalReadingTime, com.example.mybookshelf.UIMaster.filterValidEntries.
Referenced by com.example.mybookshelf.UIMaster.loadChartDataAsync.
ArrayList< BarEntry > com.example.mybookshelf.UIMaster.filterValidEntries(ArrayList< BarEntry > entries)
Filters out invalid BarEntry objects based on specific criteria. This method iterates through a list of BarEntry objects and checks each entry's year-month value. It ensures that the year is between 2000 and 2030 and the month is within the range of 1 to 12. Only entries meeting these conditions are added to the validEntries list, which is then returned. entries List of BarEntry objects to be filtered
Referenced by com.example.mybookshelf.UIMaster.setupChart.
ArrayList< BarEntry > com.example.mybookshelf.UIMaster.convertMinutesToHours(ArrayList< BarEntry > entries)
Converts a list of BarEntries from minutes to hours.
Referenced by com.example.mybookshelf.UIMaster.setupChart.
void com.example.mybookshelf.UIMaster.configureAxes()
Configures the X and Y axes of a bar chart.
References com.example.mybookshelf.UIMaster.barChart.
Referenced by com.example.mybookshelf.UIMaster.setupChart.
void com.example.mybookshelf.UIMaster.configureChart()
Configures the chart with default settings and animations.
References com.example.mybookshelf.UIMaster.barChart.
Referenced by com.example.mybookshelf.UIMaster.setupChart.
void com.example.mybookshelf.UIMaster.displayTotalReadingTime(ArrayList< BarEntry > entriesInHours)
Displays the total reading time by summing up entries and updating a TextView.
Referenced by com.example.mybookshelf.UIMaster.setupChart.
void com.example.mybookshelf.UIMaster.showErrorMessage()
Displays a short toast message indicating failure to load reading statistics.
Referenced by com.example.mybookshelf.UIMaster.loadChartDataAsync.
void com.example.mybookshelf.UIMaster.setupNavigationButtons()
Sets up the navigation buttons with their respective click listeners.
References com.example.mybookshelf.UIMaster.handleListSearch, com.example.mybookshelf.UIMaster.nav_searchBtn, com.example.mybookshelf.UIMaster.nav_StatsBtn, com.example.mybookshelf.UIMaster.navigateToGoals, com.example.mybookshelf.UIMaster.navigateToSettings, com.example.mybookshelf.UIMaster.navigateToStats.
Referenced by com.example.mybookshelf.UIMaster.navigateToStartingPage.
void com.example.mybookshelf.UIMaster.filterBooks(String titleQuery, String selectedAuthor, String selectedGenre)
Filters books based on title, author, and genre queries. This method iterates over a map of book views and their corresponding Book objects. It checks if each book matches the provided title query, author, and genre filters. If a book meets all criteria, its view is set to visible; otherwise, it is hidden.
References com.example.mybookshelf.UIMaster.bookViewMap, com.example.mybookshelf.dataClass.Book.getAuthor, com.example.mybookshelf.dataClass.Book.getGenre, com.example.mybookshelf.dataClass.Book.getName.
Referenced by com.example.mybookshelf.UIMaster.handleListSearch.
Button com.example.mybookshelf.UIMaster.createStyledGridButton(String text, View.OnClickListener listener)
Creates a styled button with specified text and click listener.
void com.example.mybookshelf.UIMaster.toggleVisibilityAnimated(RelativeLayout layout)
Toggles the visibility of a RelativeLayout with an animated scale effect.