com::example::mybookshelf::Authenticator
DataBaseConnection com.example.mybookshelf.Authenticator.db
Referenced by com.example.mybookshelf.Authenticator.Authenticator, com.example.mybookshelf.Authenticator.checkLogin, com.example.mybookshelf.Authenticator.register, com.example.mybookshelf.Authenticator.setDb.
final MainActivity com.example.mybookshelf.Authenticator.context
Referenced by com.example.mybookshelf.Authenticator.Authenticator, com.example.mybookshelf.Authenticator.clearStoredToken, com.example.mybookshelf.Authenticator.getToken, com.example.mybookshelf.Authenticator.getUid, com.example.mybookshelf.Authenticator.getUsername, com.example.mybookshelf.Authenticator.saveToken.
final ExecutorService com.example.mybookshelf.Authenticator.executorService
Referenced by com.example.mybookshelf.Authenticator.checkLogin.
final Handler com.example.mybookshelf.Authenticator.mainHandler
Referenced by com.example.mybookshelf.Authenticator.postToMain.
final String com.example.mybookshelf.Authenticator.KEY_ALIAS
Referenced by com.example.mybookshelf.Authenticator.getToken, com.example.mybookshelf.Authenticator.saveToken.
com.example.mybookshelf.Authenticator.Authenticator(MainActivity context)
References com.example.mybookshelf.Authenticator.context, com.example.mybookshelf.Authenticator.db.
void com.example.mybookshelf.Authenticator.checkLogin(User attempt, BiConsumer< Boolean, Integer > callback)
References com.example.mybookshelf.Authenticator.db, com.example.mybookshelf.Authenticator.executorService, com.example.mybookshelf.dataClass.User.getPassword, com.example.mybookshelf.dataClass.User.getUser, com.example.mybookshelf.Authenticator.postToMain.
void com.example.mybookshelf.Authenticator.register(String username, String password, String email)
References com.example.mybookshelf.Authenticator.db.
void com.example.mybookshelf.Authenticator.saveToken(Context context, String token, int uid, String username)
References com.example.mybookshelf.Authenticator.context, com.example.mybookshelf.Authenticator.KEY_ALIAS.
int com.example.mybookshelf.Authenticator.getUid(Context context)
References com.example.mybookshelf.Authenticator.context.
String com.example.mybookshelf.Authenticator.getToken(Context context)
References com.example.mybookshelf.Authenticator.context, com.example.mybookshelf.Authenticator.KEY_ALIAS.
String com.example.mybookshelf.Authenticator.getUsername(Context context)
References com.example.mybookshelf.Authenticator.context.
void com.example.mybookshelf.Authenticator.setDb(DataBaseConnection db)
References com.example.mybookshelf.Authenticator.db.
void com.example.mybookshelf.Authenticator.postToMain(Runnable task)
References com.example.mybookshelf.Authenticator.mainHandler.
Referenced by com.example.mybookshelf.Authenticator.checkLogin.
static void com.example.mybookshelf.Authenticator.clearStoredToken(Context context)
References com.example.mybookshelf.Authenticator.context.
Referenced by com.example.mybookshelf.UIMaster.navigateToSettings, com.example.mybookshelf.MainActivity.onCreate.