com::example::mybookshelf::dataClass::Goal
int com.example.mybookshelf.dataClass.Goal.id
boolean com.example.mybookshelf.dataClass.Goal.completed
int com.example.mybookshelf.dataClass.Goal.progress
int com.example.mybookshelf.dataClass.Goal.target
String com.example.mybookshelf.dataClass.Goal.bookName
String com.example.mybookshelf.dataClass.Goal.goal
String com.example.mybookshelf.dataClass.Goal.frequenzy
boolean com.example.mybookshelf.dataClass.Goal.reminder
LocalDateTime com.example.mybookshelf.dataClass.Goal.deadline
com.example.mybookshelf.dataClass.Goal.Goal(int id, int progress, int target, String goalType, String goal, LocalDateTime deadline)
com.example.mybookshelf.dataClass.Goal.Goal(int id, int progress, int target, String goalType, String goal)
com.example.mybookshelf.dataClass.Goal.Goal(int id, int progress, int target, String bookName, String goalType, String goal)
int com.example.mybookshelf.dataClass.Goal.getId()
Returns the ID of the object.
Referenced by com.example.mybookshelf.dataClass.User.addGoal, com.example.mybookshelf.LayoutManager.CustomGoalAdapter.createGoalBox, com.example.mybookshelf.GoalHandler.handleBookAdded, com.example.mybookshelf.GoalHandler.handleBookChange, com.example.mybookshelf.GoalHandler.handleBookRemoved.
boolean com.example.mybookshelf.dataClass.Goal.isCompleted()
Checks if the task is completed.
int com.example.mybookshelf.dataClass.Goal.getProgress()
Returns the current progress value.
Referenced by com.example.mybookshelf.DataBaseConnection.addGoal, com.example.mybookshelf.LayoutManager.CustomGoalAdapter.createGoalBox, com.example.mybookshelf.GoalHandler.handleBookAdded, com.example.mybookshelf.GoalHandler.handleBookChange, com.example.mybookshelf.GoalHandler.handleBookRemoved.
int com.example.mybookshelf.dataClass.Goal.getTarget()
Returns the target value.
Referenced by com.example.mybookshelf.DataBaseConnection.addGoal, com.example.mybookshelf.LayoutManager.CustomGoalAdapter.createGoalBox, com.example.mybookshelf.GoalHandler.handleBookAdded, com.example.mybookshelf.GoalHandler.handleBookChange, com.example.mybookshelf.GoalHandler.handleBookRemoved.
String com.example.mybookshelf.dataClass.Goal.getGoal()
Returns the current goal.
Referenced by com.example.mybookshelf.DataBaseConnection.addGoal, com.example.mybookshelf.LayoutManager.CustomGoalAdapter.createGoalBox, com.example.mybookshelf.GoalHandler.handleBookAdded, com.example.mybookshelf.GoalHandler.handleBookChange, com.example.mybookshelf.GoalHandler.handleBookRemoved, com.example.mybookshelf.notifications.NotificationScheduler.sendGoalCompletedNotification.
String com.example.mybookshelf.dataClass.Goal.getBookName()
Returns the name of the book.
Referenced by com.example.mybookshelf.DataBaseConnection.addGoal, com.example.mybookshelf.GoalHandler.handleBookAdded, com.example.mybookshelf.GoalHandler.handleBookChange, com.example.mybookshelf.GoalHandler.handleBookRemoved.
String com.example.mybookshelf.dataClass.Goal.getFrequenzy()
Returns the value of frequenzy.
Referenced by com.example.mybookshelf.DataBaseConnection.addGoal, com.example.mybookshelf.LayoutManager.CustomGoalAdapter.createGoalBox.
void com.example.mybookshelf.dataClass.Goal.setId(int id)
Sets the ID of the object.
Referenced by com.example.mybookshelf.DataBaseConnection.getAllGoalsForUser.
String com.example.mybookshelf.dataClass.Goal.toString()
Returns a string representation of the Goal object.
void com.example.mybookshelf.dataClass.Goal.setProgress(int progress)
Sets the progress to the specified value.
Referenced by com.example.mybookshelf.GoalHandler.handleBookAdded, com.example.mybookshelf.GoalHandler.handleBookChange, com.example.mybookshelf.GoalHandler.handleBookRemoved.
LocalDateTime com.example.mybookshelf.dataClass.Goal.getDeadline()
Returns the deadline.